---
- name: "Install common utils"
  hosts: all
  roles:
    - common
  tags:
    - common

- name: "Cluster"
  hosts: k3s_cluster
  roles:
    - k3s/common
  tags:
    - k3s/common

- name: "Master"
  hosts: master
  roles:
    - k3s/master
  tags:
    - k3s/master
