---
- name: "Install common utils"
  hosts: all
  roles:
    - common
  tags:
    - common



#- name: "Cluster"
#  hosts: k8s_cluster
#  roles:
#    - k8s/common
#  tags:
#    - k8s/common
#
#- name: "Master"
#  hosts: master
#  roles:
#    - k8s/master
#  tags:
#    - k8s/master
