---
- name: Install dependencies
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - gnupg
      - curl
      - python3-pip
    state: present
    update_cache: true

- name: Update apt packages
  become: true
  apt:
    update_cache: yes

- name: Create directory for Docker GPG keyrings
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  become: true
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc

- name: Set permissions for Docker GPG key
  become: true
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository to Apt sources
  become: true
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [arch={{ architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    create: yes

- name: Update apt packages again
  become: true
  apt:
    update_cache: yes

- name: Install Docker with a specific version
  become: true
  apt:
    name: 
      - docker-ce={{ docker_version }}
      - docker-ce-cli={{ docker_version }}
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    allow_downgrades: yes

- name: Add current user to docker group
  become: true
  user:
    name: "{{ansible_user_id}}"
    groups: docker
    append: yes  # Add the user to the group without removing from other groups

- name: Restart Docker service
  become: true
  systemd:
    name: docker
    state: restarted
