---
- name: Install dependencies
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - gnupg
      - docker.io
      - docker-compose
    state: latest
    update_cache: true
