---
- name: Install useful utils
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 3600
    state: present
    name:
      - netcat
      - htop
      - dnsutils
      - ncdu
      - net-tools

- name: apt upgrade
  become: true
  apt:
    upgrade: safe
    cache_valid_time: 3600
    update_cache: yes
    state: present
